# Generated by Django 2.1.5 on 2019-01-31 09:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('dependents', models.PositiveIntegerField(help_text='Number of <b>Client</b> family dependents', validators=[django.core.validators.MinValueValidator(0)])),
                ('income', models.PositiveIntegerField(help_text='Amount of income of <b>Client</b> in a year', validators=[django.core.validators.MinValueValidator(0)])),
                ('marital_status', models.CharField(choices=[('single', 'single'), ('married', 'married')], max_length=1)),
                ('risk_questions', models.CharField(choices=[('[0, 0, 1]', 'responsible'), ('[0, 1, 0]', 'regular'), ('[1, 0, 0]', 'economic')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('ownership_status', models.CharField(choices=[('owned', 'owned'), ('mortgaged', 'mortgaged')], help_text='House ownership of <b>owner</b> house', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.PositiveIntegerField(default=None, null=True)),
                ('risk_scores', models.CharField(choices=[('0', 'economic'), ('1', 'regular'), ('2', 'regular'), ('3', 'responsible')], default=None, max_length=1, null=True)),
                ('auto', models.CharField(choices=[('0', 'economic'), ('1', 'regular'), ('2', 'regular'), ('3', 'responsible')], max_length=1, null=True)),
                ('home', models.CharField(choices=[('0', 'economic'), ('1', 'regular'), ('2', 'regular'), ('3', 'responsible')], max_length=20, null=True)),
                ('life', models.CharField(choices=[('0', 'economic'), ('1', 'regular'), ('2', 'regular'), ('3', 'responsible')], max_length=20, null=True)),
                ('umbrella', models.CharField(choices=[('0', 'economic'), ('1', 'regular'), ('2', 'regular'), ('3', 'responsible')], max_length=20, null=True)),
                ('disability', models.CharField(max_length=20, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='core.Client')),
                ('houses', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='riskscore', to='core.House')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(help_text='Fabrication year of <b>owner</b> car', validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2019)])),
            ],
        ),
        migrations.AddField(
            model_name='riskscore',
            name='vehicles',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='riskscore', to='core.Vehicle'),
        ),
        migrations.AddField(
            model_name='client',
            name='houses',
            field=models.ManyToManyField(blank=True, to='core.House'),
        ),
        migrations.AddField(
            model_name='client',
            name='vehicles',
            field=models.ManyToManyField(blank=True, to='core.Vehicle'),
        ),
    ]
